spring:
  application:
    name: sg-lta-mcp-server
  ai:
    mcp:
      server:
        name: sg-lta-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "Provides SG bus arrival tools"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
  main:
    banner-mode: off

server:
  port: 8689
  servlet:
    contextPath: /mcp

sg-lta:
  base-url: http://localhost:8688

management:
  endpoints:
    web:
      exposure:
        include: health  # Only expose /actuator/health
  endpoint:
    health:
      show-details: never
